Improvement: User/Library header page
ditrit/leto-modelizer-admin pull request #107
Opened 2024-03-06 14:03 UTC by Zorin95670

2024-03-06 16:21 UTC, justinehell requested changes

2024-03-06 16:21 UTC, justinehell commented on src/components/avatar/LibraryAvatar.vue
> +  loadLibraryIcon();
await loadLibraryIcon();

2024-03-06 16:21 UTC, justinehell commented on src/components/tooltip/UserTooltip.vue
> +  },
I don't see it used in the template

2024-03-06 16:21 UTC, justinehell commented on src/pages/LibraryPage.vue
> +    });
jump line before `.finally(...)`

2024-03-06 16:21 UTC, justinehell commented on src/pages/LibraryPage.vue
> + * Load user picture by its login.
just `Load user by its login` no?

2024-03-07 09:08 UTC, Zorin95670 commented on src/components/avatar/LibraryAvatar.vue
> +  loadLibraryIcon();
done

2024-03-07 09:08 UTC, Zorin95670 commented on src/components/tooltip/UserTooltip.vue
> +  },
done

2024-03-07 09:09 UTC, Zorin95670 commented on src/pages/LibraryPage.vue
> + * Load user picture by its login.
yes done!

2024-03-07 09:28 UTC, justinehell approved these changes

2024-03-07 09:28 UTC, merged