Feature: update roles table
ditrit/leto-modelizer-admin pull request #121
Opened 2024-03-25 11:18 UTC by Zorin95670

2024-03-25 15:46 UTC, justinehell requested changes

2024-03-25 15:46 UTC, justinehell commented on src/components/tables/RolesTable.vue
> +        :name="props.filterName"
Remove `props` from all `props.[name]`

ex: just write `:name="filterName"`

2024-03-26 09:47 UTC, Zorin95670 commented on src/components/tables/RolesTable.vue
> +        :name="props.filterName"
done

2024-03-26 10:34 UTC, justinehell approved these changes

2024-03-26 10:38 UTC, merged