Feature/add user group page
ditrit/leto-modelizer-admin pull request #56
Opened 2023-12-20 10:42 UTC by k-y0u

Resolves #16

2023-12-20 13:39 UTC, justinehell requested changes

2023-12-20 13:39 UTC, justinehell commented on src/services/UserGroupService.js
> + * get userGroup by id.
Get

2023-12-20 13:39 UTC, justinehell commented on changelog.md
> +  * Display all information of a user Group.
- user groups.
- User Group
- user Group
--> inconsistent

2023-12-21 09:46 UTC, k-y0u commented on changelog.md
> +  * Display all information of a user Group.
done

2023-12-21 09:46 UTC, k-y0u commented on src/services/UserGroupService.js
> + * get userGroup by id.
done

2023-12-21 09:55 UTC, justinehell approved these changes

2023-12-21 10:39 UTC, Zorin95670 approved these changes

2023-12-21 10:39 UTC, merged